dist: xenial
language: minimal

services:
  - docker

before_install:
  - docker pull altairwei/wiznoteplus-build

script:
  - docker run -v $PWD:/WizNotePlus -v $PWD/.build:/build-WizNotePlus altairwei/wiznoteplus-build /WizNotePlus/.ci/build.sh /WizNotePlus /build-WizNotePlus