name: Conan Build
on:
  push:
    branches:
      - master
      - release-*
      - feat-GithubActions

jobs:
  build_linux:
    name: build-WizNotePlus-linux
    runs-on: ubuntu-16.04
    env:
      QT_VERSION_MAJOR: 5
      QT_VERSION_MINOR: 14
      QT_VERSION_PATCH: 1
      QT_VERSION: 5.14.1
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y -qq --no-install-recommends git make cmake g++ wget
          sudo apt-get install -y -qq --no-install-recommends xvfb libgl-dev fcitx fcitx-frontend-qt5
      - name: Install Qt library
        env: 
          QT_INSTALL_TARGET_DIR: /opt/Qt
          QT_INSTALL_PREFIX: /opt/Qt/${{ env.QT_VERSION }}/gcc_64
        run: |
          echo "Qt will be installed at " $QT_INSTALL_PREFIX
          wget http://download.qt.io/archive/qt/5.14/5.14.1/qt-opensource-linux-x64-5.14.1.run
          mv qt-opensource-linux-x64-5.14.1.run qt.run && sudo chmod a+x qt.run
          ./qt.run --verbose --script .ci/qt-auto-install.qs --platform minimal
      - name: Download deploy tool
        run: |
          wget https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage
          sudo mv linuxdeployqt-continuous-x86_64.AppImage /usr/bin/linuxdeployqt
          sudo chmod a+x /usr/bin/linuxdeployqt
      - name: Install and config conan
        run: |
          pip install conan
          conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
          conan remote add conan-community https://api.bintray.com/conan/conan-community/conan
          conan remote add wiznoteplus https://api.bintray.com/conan/altairwei/conan
          conan profile new default --detect
          conan profile update settings.compiler.libcxx=libstdc++11 default
      - name: Build project
        env:
          QT_INSTALL_PREFIX: /opt/Qt/${{ env.QT_VERSION }}/gcc_64
        run: |
          echo "CWD: " $(pwd)
          echo "QT_INSTALL_PREFIX: " $QT_INSTALL_PREFIX
          mkdir -p _build
          ./.ci/build.sh $(pwd) $(pwd)/_build
      - uses: actions/upload-artifact@v1
        with:
          name: Linux_Dist
          path: _build/package/dist